kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: centos
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centos
        image: joshbav/amgen-centos
        command: ["./startup.sh"]
        resources:
          requests:
            memory: 100M
            cpu: 0.1
        securityContext:
          # Note in production you would not use full privileged 
          privileged: true
